### ISSUE TITLE
Can you share train_LR_bicubic datas?

### ISSUE THREAD

**Issue by sylivahf** [dong-won-jang/DRCA#1]
Can you share train_LR_bicubic datas? i plan to reappear your jobs.
Thanks, very ...very!

**Comment by dong-won-jang** [comment]
You can download dataset here: DIV2K (https://data.vision.ee.ethz.ch/cvl/DIV2K/) and Flickr 2K (http://cv.snu.ac.kr/research/EDSR/Flickr2K.tar)

**Comment by sylivahf** [comment]
Thank you so much!
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "dong-won-jang"<notifications@github.com&gt;; 
发送时间: 2020年4月12日(星期天) 中午1:23
收件人: "dong-won-jang/DRCA"<DRCA@noreply.github.com&gt;; 
抄送: "黄凤"<156609574@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dong-won-jang/DRCA] Can you share train_LR_bicubic datas? (#1)





 
You can download dataset here: DIV2K (https://data.vision.ee.ethz.ch/cvl/DIV2K/) and Flickr 2K (http://cv.snu.ac.kr/research/EDSR/Flickr2K.tar)
